mishmar/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import ArmingAllMonthView, ArmingPersonalMonthView, EventCreateView, EventListView, EventUpdateView, GunListView, IpBanListView, OrganizationDetailView, PostCreateView, PostListView, PostUpdateView, ShifttableView, ValidationLogMonthView, data_usage_view, delete_events_data_view, delete_logs_data_view, delete_organization_data_view, organization_shift_view, staff_panel_view
from .views import ServedSumListView, ServedSumShiftDetailView, ServedSumReinforcementsDetailView
from .views import OrganizationSuggestionView, OrganizationCreateView, OrganizationListView
from .views import organization_update
from .views import ArmingDayView, ArmingLogUpdate, ArmingCreateView, Validation_Log_Signature, ArmingRequestView, ArmingRequestDetailView, ArmingRequestListView

urlpatterns = [
    path("", views.home, name="Home"),
    path("serve/", views.shift_view, name="Serve"),
    path("organization/", OrganizationListView.as_view(), name="Organization"),
    path("serve/sum", ServedSumListView.as_view(), name="Served-sum"),
    path("settings/", views.settings_view, name="Settings"),
    path("organization/<int:pk>/update", organization_update, name="organization-update"),
    path("shift/<int:pk>/update", views.shift_update_view, name="shift-update"),
    path('organization/<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('serve/sum/shift/<int:pk>/', ServedSumShiftDetailView.as_view(), name='served-sum-shift'),
    path('serve/sum/reinforcement/<int:pk>/', ServedSumReinforcementsDetailView.as_view(), name='served-sum-reinforcement'),
    path('organization/table/shift/<int:pk>/', ShifttableView.as_view(), name='organization-table-shift'),
    path("organization/<int:pk>/suggestion", OrganizationSuggestionView.as_view(), name="organization-suggestion"),
    path("organization/new", OrganizationCreateView.as_view(), name="organization-new"),
    path('<int:year>/<str:month>/<int:day>/', ArmingDayView.as_view(), name="armingday"),
    path('<int:year>/<str:month>/',  ArmingPersonalMonthView.as_view(), name="armingmonth"),
    path('<int:year>/<str:month>/all',  ArmingAllMonthView.as_view(), name="armingmonth-all"),
    path('signature/<int:pk>/',  ArmingLogUpdate.as_view(), name="signature"),
    path('ArmingLog/new/',  ArmingCreateView.as_view(), name="arming-new"),
    path('validation/signature', Validation_Log_Signature, name="validation-signature"),
    path('arminglog/changerequest/new', ArmingRequestView.as_view(), name="arming-changerequest"),
    path('arminglog/request/<int:pk>/', ArmingRequestDetailView.as_view(), name="arming-request"),
    path('arminglog/requests/', ArmingRequestListView.as_view(), name="arming-requests-list"),
    path('staff/panel/', staff_panel_view, name="staff-panel"),
    path('organization/design/', organization_shift_view, name="organization-design"),
    path('post/new', PostCreateView.as_view(), name="post-new"),
    path('post/update/<int:pk>/', PostUpdateView.as_view(), name="post-update"),
    path('posts/', PostListView.as_view(), name="post-list"),
    path('event/new', EventCreateView.as_view(), name="event-new"),
    path('event/update/<int:pk>/', EventUpdateView.as_view(), name="event-update"),
    path('event/list', EventListView.as_view(), name="event-list"),
    path('ip/ban/list', IpBanListView.as_view(), name="ipban-list"),
    path('data/usage/', data_usage_view, name="data-usage"),
    path('data/organizations/delete', delete_organization_data_view, name="delete-organization-data"),
    path('data/logs/delete', delete_logs_data_view, name="delete-logs-data"),
    path('data/events/delete', delete_events_data_view, name="delete-events-data"),
    path('gun/list', GunListView.as_view(), name="gun-list"),
    path('<int:year>/<str:month>/validation/', ValidationLogMonthView.as_view(), name="validation-month"),
]

mishmardjango/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('register/', user_views.register, name="register"),
    path('profile/', user_views.profile, name="profile"),
    path('login/', user_views.login, name="login"),
    path('user/list', user_views.UserListView.as_view(), name="user-list"),
    path('quality/list/', user_views.QualityUserListView.as_view(), name="quality-list"),
    path('password/change/<int:pk>/', user_views.UserPasswordUpdateView.as_view(), name="password-change"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name="password_reset"),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name="password_reset_confirm"),
    path('password-reset-complete/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_complete.html'),
         name="password_reset_complete"),
    path("", include("mishmar.urls"))
]
handler404 = 'mishmar.views.error_404_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mishmar/models.py
from time import time
from django import forms
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.mail import send_mail
import datetime
from jsonfield import JSONField
import collections



class Post(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now, verbose_name="תאריך")
    title = models.CharField(max_length=30, verbose_name="כותרת")
    text = models.TextField(blank=True, verbose_name="טקסט")

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "פוסט"
        verbose_name_plural = "פוסטים"


class Settings(models.Model):
    submitting = models.BooleanField(default=True, verbose_name="ניתן להגיש/לשנות הגשות")
    pin_code = models.IntegerField(default=1234, verbose_name="קוד זיהוי")
    officer = models.CharField(max_length=20, verbose_name="קצין מתקן")
    city = models.CharField(max_length=100, verbose_name="עיר")
    max_seq0 = models.IntegerField(default=2, verbose_name="מספר רצפים מקסימלי לילה לצהריים")
    max_seq1 = models.IntegerField(default=2, verbose_name="מספר רצפים מקסימלי צהריים לבוקר")
    version = models.CharField(max_length=10, default="1.0", verbose_name="גרסה")
    friday_morning = models.BooleanField(default=False, verbose_name="שישי בוקר נחשב במינימום הגשות?", blank=True)
    friday_noon = models.BooleanField(default=False, verbose_name="שישי בצהריים נחשב במינימום הגשות?", blank=True)
    num_mags = models.PositiveIntegerField(default=3, verbose_name="מספר מחסניות")
    hand_cuffs = models.PositiveIntegerField(default=8, verbose_name="מספר אזיקים")
    num_mag_cases = models.PositiveIntegerField(default=8, verbose_name="מספר פונדות")
    num_gun_cases = models.PositiveIntegerField(default=8, verbose_name="מספר נרתיקים")


    def __str__(self):
        return "הגדרות"

class OrganizationShift(models.Model):
    title = models.CharField(max_length=200, verbose_name="משמרת")
    index = models.IntegerField(default=1, verbose_name="מספר משמרת")
    shift_num = models.IntegerField(default=1, verbose_name="סוג משמרת")
    sub_title = models.CharField(max_length=200, verbose_name="כותרת משמרת", blank=True, null=True)
    opening = models.BooleanField(default=False, verbose_name="פתיחה", blank=True)
    manager = models.BooleanField(default=False, verbose_name="אחמש", blank=True)
    pull = models.BooleanField(default=False, verbose_name="משיכה", blank=True)

    def __str__(self):
        return f'{self.title} - {self.sub_title} - {self.id} - {self.shift_num}'
    
    class Meta:
        verbose_name = "משמרת מבנה סידור"
        verbose_name_plural = "משמרות מבנה סידור"

class Organization1(models.Model):
    date = models.DateField(default=timezone.now)
    num_weeks = models.IntegerField(default=2, blank=False)
    published = models.BooleanField(default=False, verbose_name="פרסום")
    weeks_data = JSONField()

    def __str__(self):
        return f'{self.date}'

    def get_absolute_url(self):
        return reverse("organization-update", kwargs={"pk": self.pk})
    
    class Meta:
        verbose_name = "סידור עבודה"
        verbose_name_plural = "סידורי עבודה"


class Shift(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization1, on_delete=models.CASCADE, blank=True, null=True)
    notes = models.TextField(max_length=200, blank=True, verbose_name="הערות")
    seq_night = models.IntegerField(default=0, verbose_name="מ\"ס רצפים לילה לצהריים")
    seq_noon = models.IntegerField(default=0, verbose_name="מ\"ס רצפים צהריים לבוקר")
    weeks_data = JSONField()

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} ({self.user}) - {self.organization.date}'

    def get_absolute_url(self):
        return reverse("shift-update", kwargs={"pk": self.pk})
    
    class Meta:
        verbose_name = "הגשה"
        verbose_name_plural = "הגשות"


class Event(models.Model):
    nickname = models.CharField(default="", max_length=20, verbose_name="כינוי", blank=False)
    date2 = models.DateField(default=timezone.now, verbose_name="תאריך")
    description = models.CharField(default="", max_length=50, verbose_name="תאור")

    def __str__(self):
        return f'{self.nickname} {self.date2}'

    class Meta:
        verbose_name = "אירוע"
        verbose_name_plural = "אירועים"


class IpBan(models.Model):
    ipaddress = models.GenericIPAddressField(verbose_name="כתובת IP")
    num_tries = models.IntegerField(default=0, verbose_name="מספר ניסיונות")

    def __str__(self):
        return f'{self.ipaddress} ({self.num_tries})'

    class Meta:
        verbose_name = "חסימת IP"
        verbose_name_plural = "חסימות IP"


class Gun(models.Model):
    full_name = models.CharField(verbose_name="שם מלא", max_length=50)
    short_name = models.CharField(verbose_name="שם קצר", max_length=20)

    def __str__(self):
        return self.short_name
    
    class Meta:
        verbose_name = "נשק"
        verbose_name_plural = "נשקים"

class ValidationLog(models.Model):
    date = models.DateField(verbose_name="תאריך", default=timezone.now)
    num_guns_safe_m = models.IntegerField(verbose_name="מספר נשקים בכספת בוקר", blank=True, default=0)
    num_guns_shift_m = models.IntegerField(verbose_name="מספר נשקים במשמרת בוקר", blank=True, default=0)
    time_checked_m = models.TimeField(verbose_name="שעת בדיקה בוקר", blank=True, default=timezone.now)
    name_checked_m = models.CharField(max_length=50, verbose_name="שם בודק בוקר", blank=True, default="")
    sig_m = models.TextField(verbose_name="חתימה בוקר", blank=True, null=True)
    num_guns_safe_a = models.IntegerField(verbose_name="מספר נשקים בכספת צהריים", blank=True, default=0)
    num_guns_shift_a = models.IntegerField(verbose_name="מספר נשקים במשמרת צהריים", blank=True, default=0)
    time_checked_a = models.TimeField(verbose_name="שעת בדיקה צהריים", blank=True, default=timezone.now)
    name_checked_a = models.CharField(max_length=50, verbose_name="שם בודק צהריים", blank=True, default="")
    sig_a = models.TextField(verbose_name="חתימה צהריים", blank=True, null=True)
    num_guns_safe_n = models.IntegerField(verbose_name="מספר נשקים בכספת לילה", blank=True, default=0)
    num_guns_shift_n = models.IntegerField(verbose_name="מספר נשקים במשמרת לילה", blank=True, default=0)
    time_checked_n = models.TimeField(verbose_name="שעת בדיקה לילה", blank=True, default=timezone.now)
    name_checked_n = models.CharField(max_length=50, verbose_name="שם בודק לילה", blank=True, default="")
    sig_n = models.TextField(verbose_name="חתימה לילה", blank=True, null=True)


    def __str__(self):
        return str(self.date)
    
    class Meta:
        verbose_name = "בדיקת נשקים"
        verbose_name_plural = "בדיקות נשקים"


class Arming_Log(models.Model):
    date = models.DateField(default=timezone.now, verbose_name="תאריך", blank=False)
    data = JSONField()

    def get_absolute_url(self):
        return reverse("signature", kwargs={"pk": self.pk})

    def __str__(self):
        return self.date.strftime("%d/%m/%Y")
    
    class Meta:
        verbose_name = "הזנה ביומן חימוש"
        verbose_name_plural = "הזנות ביומן חימוש"

class ArmingRequest(models.Model):
    log = models.ForeignKey(Arming_Log, on_delete=models.CASCADE, verbose_name="הזנה ביומן חימוש", blank=False)
    input_num = models.IntegerField(verbose_name="מספר הזנה", blank=False, default=1)
    username = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="שם משתמש", blank=False, null=True)
    id_num = models.CharField(max_length=9, verbose_name="תעודת זהות", blank=False, default="")
    shift_num = models.IntegerField(verbose_name="מספר משמרת", default=1, blank=False)
    time_in = models.TimeField(default=timezone.now, verbose_name="זמן כניסה", blank=False)
    gun = models.ForeignKey(Gun, on_delete=models.CASCADE, verbose_name="מספר נשק", blank=False)
    num_mags = models.IntegerField(default=2, verbose_name="מספר מחסניות", blank=False)
    hand_cuffs = models.IntegerField(default=6, verbose_name="אזיקים", blank=False)
    gun_case = models.IntegerField(default=6, verbose_name="פונדה", blank=False)
    mag_case = models.IntegerField(default=6, verbose_name="נרתיק", blank=False)
    keys = models.BooleanField(default=False, verbose_name="מפתחות", blank=False)
    radio = models.BooleanField(default=False, verbose_name="קשר", blank=False)
    radio_kit = models.BooleanField(default=False, verbose_name="ערכת שמע", blank=False)
    time_out = models.TimeField(verbose_name="זמן יציאה", blank=True, null=True)
    signature_in = models.TextField(verbose_name="חתימת כניסה", null=True, blank=True)
    signature_out = models.TextField(verbose_name="חתימת יציאה", null=True, blank=True)
    read = models.BooleanField(default=False, verbose_name="טופל?", blank=False)
    reason = models.TextField(verbose_name="סיבה", blank=False, default="")

    def __str__(self):

        return self.log.data[str(self.input_num)]["name"] + " " + str(self.log.date)

    class Meta:
        verbose_name = "בקשה לשינוי יומן חימוש"
        verbose_name_plural = "בקשות לשינוי יומן חימוש"

mishmar/forms.py
from django import forms
from users.models import UserSettings as UserSettings
from .models import Settings as Settings
from django.contrib.auth.models import User


class QualityUpdateForm(forms.ModelForm):
    night = forms.IntegerField(min_value=0)
    sat_night = forms.IntegerField(min_value=0)
    sat_morning = forms.IntegerField(min_value=0)
    sat_noon = forms.IntegerField(min_value=0)

    class Meta:
        model = UserSettings
        fields = ['user', 'night', 'sat_night', 'sat_morning', 'sat_noon']



class SettingsForm(forms.ModelForm):
    pin_code = forms.IntegerField(required=True)
    officer = forms.CharField(max_length=20)
    city = forms.CharField(max_length=30)
    max_seq0 = forms.IntegerField(required=True)
    max_seq1 = forms.IntegerField(required=True)
    friday_morning = forms.BooleanField(required=False)
    friday_noon = forms.BooleanField(required=False)
    num_mags = forms.IntegerField(required=True)
    hand_cuffs = forms.IntegerField(required=True)
    num_mag_cases = forms.IntegerField(required=True)
    num_gun_cases = forms.IntegerField(required=True)


    class Meta:
        model = Settings
        fields = ["pin_code", "officer", "city", "max_seq0", "max_seq1", "friday_morning", "friday_noon", "num_mags", "hand_cuffs", "num_mag_cases", "num_gun_cases"]

mishmar/templates/mishmar/Served_sum_list.html
{% extends "mishmar/base.html" %}
{% block content %}
    <div class="row">
    <h1>סידורים:</h1>
        <form method="POST">
        {% csrf_token %}
            <div class="row">
    <a href="{% url 'organization-new' %}" class="float">
        <i class="fa fa-plus my-float"></i>+
    </a>
    <div class="label-container">
        <div class="label-text">סידור חדש</div>
        <i class="fa fa-play label-arrow"></i>
    </div>
                </div>
        </form>
    </div>
    {% for organization in organizations %}
        <div>
        <article class="content-section">
        <h2>{{ organization.date|plus_days|date:"d.m.y" }} - {{ organization.date|date:"d.m.y" }}:</h2>
            <div class="row">
                <h6 style="margin-right: 1em; margin-top: 0.5em">פעולות:</h6>
                    <div style="margin-right: 0.5em">
            <h3><a class="article-title" href="{% url 'organization-update' organization.id %}">עדכון</a></h3>
                        </div>
                <h4 style="margin-right: 1em">|</h4>
                    <div style="margin-right: 1em; margin-left: 1em">
                        <h3><a class="article-title" href="{% url 'organization-suggestion' organization.id %}">הצעה לסידור</a></h3>
                        </div>
            </div>
            <div class="row">
                <h6 style="margin-right: 1em; margin-top: 0.5em">הגשות:</h6>
                    <div style="margin-right: 0.5em">
            <h3><a class="article-title" href="{% url 'served-sum-shift' organization.id %}">משמרות</a></h3>
                        </div>
                <h4 style="margin-right: 1em">|</h4>
                    <div style="margin-right: 1em; margin-left: 1em">
                        <h3><a class="article-title" href="{% url 'served-sum-reinforcement' organization.id %}">תגבורים</a></h3>
                        </div>
            </div>
        </article>
        </div>
            {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">ראשון</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">קודם</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">הבא</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">אחרון</a>
      {% endif %}

    {% endif %}
{% endblock content %}

mishmar/templates/mishmar/ShiftView.html
<div style="padding:10px 0">
    {% if submitting %}
    <a>מספר רצפים לילה לצהריים: </a><input required type="number" min="0" {% if shift != None %} value="{{ shift.seq_night }}" {% else %} value="0" {% endif %} name="seq_night" id="id_seq_night">
    {% else %}
        <a>מספר רצפים לילה לצהריים: </a><input required type="number" min="0" {% if shift != None %} value="{{ shift.seq_night }}" {% else %} value="0" {% endif %} name="seq_night" id="id_seq_night" disabled>
    {% endif %}
</div>
<div style="padding:10px 0">
    {% if submitting %}
    <a>מספר רצפים צהריים לבוקר: </a><input required type="number" min="0" {% if shift != None %} value="{{ shift.seq_noon }}" {% else %} value="0" {% endif %} name="seq_noon" id="id_seq_noon">
    {% else %}
    <a>מספר רצפים צהריים לבוקר: </a><input required type="number" min="0" {% if shift != None %} value="{{ shift.seq_noon }}" {% else %} value="0" {% endif %} name="seq_noon" id="id_seq_noon" disabled>
    {% endif %}
</div>
{% for week in shift_data %}
<table class="responsive-table-input-matrix" style="align-items: center">
		<thead>
		<tr>
			<th>תאריך</th>
			{% for day in days|clip_days:forloop.counter0 %}
                <th>{{ day|date:"d.m" }}</th>
                {% endfor %}
		</tr>
		<tr>
			<th></th>
			<th>ראשון</th>
			<th>שני</th>
			<th>שלישי</th>
			<th>רביעי</th>
			<th>חמישי</th>
			<th>שישי</th>
			<th>שבת</th>
		</tr>
		</thead>
		<tbody>

		<tr style="align-content: end">
			<td>בוקר</td>
        {% for field in shift_data|get_served_week:week|get_list_dict_served:"M" %}
			<td><input type="checkbox" {% if not submitting %} disabled {% endif %} {% if field|default_if_none:False == True %} checked {% endif %} name="M{{ forloop.counter }}_{{ forloop.parentloop.counter0 }}"></td>
            {% endfor %}
		</tr>
		<tr>
			<td>צהריים</td>
            {% for field in shift_data|get_served_week:week|get_list_dict_served:"A" %}
            <td><input type="checkbox" {% if not submitting %} disabled {% endif %} {% if field|default_if_none:False == True %} checked {% endif %} name="A{{ forloop.counter }}_{{ forloop.parentloop.counter0 }}"></td>
            {% endfor %}
		</tr>
		<tr>
		<td>לילה</td>
        {% for field in shift_data|get_served_week:week|get_list_dict_served:"N" %}
        <td><input type="checkbox" {% if not submitting %} disabled {% endif %} {% if field|default_if_none:False == True %} checked {% endif %} name="N{{ forloop.counter }}_{{ forloop.parentloop.counter0 }}"></td>
        {% endfor %}
		</tr>
        <tr>
		<td>↑לילה<br>↓משיכה</td>
			<td>↑לילה<br>↓משיכה</td>
			<td>↑לילה<br>↓משיכה</td>
            <td>↑לילה<br>↓משיכה</td>
            <td>↑לילה<br>↓משיכה</td>
            <td>↑לילה<br>↓משיכה</td>
            <td>↑לילה<br>↓משיכה</td>
            <td>↑לילה<br>↓משיכה</td>
		</tr>
        <tr>
			<td>משיכה</td>
            {% for field in shift_data|get_served_week:week|get_list_dict_served:"P" %}
            <td><input type="checkbox" {% if not submitting %} disabled {% endif %} {% if field|default_if_none:False == True %} checked {% endif %} name="P{{ forloop.counter }}_{{ forloop.parentloop.counter0 }}"></td>
            {% endfor %}
		</tr>
        <tr>
			<td>תגבור</td>
            {% for field in shift_data|get_served_week:week|get_list_dict_served:"R" %}
            <td><input type="checkbox" {% if not submitting %} disabled {% endif %} {% if field|default_if_none:False == True %} checked {% endif %} name="R{{ forloop.counter }}_{{ forloop.parentloop.counter0 }}"></td>
            {% endfor %}
		</tr>
		<tr>
			<td>הערות</td>
            {% for field in shift_data|get_served_week:week|get_list_dict_served:"notes" %}
                <td><textarea name="notes{{ forloop.counter }}_{{ forloop.parentloop.counter0 }}" {% if not submitting %} disabled {% endif %} >{{ field|default_if_none:"" }}</textarea></td>
            {% endfor %}
		</tr>
		</tbody>
	</table>
{% endfor %}
            <div dir="rtl" class="row">
                <notes >
                    <a>הערות:</a>
                </notes>
                <div STYLE="margin-top: 1.5em">
                    <textarea name="notesArea" class="notesArea" {% if not submitting %} disabled {% endif %}>{{ notes_text }}</textarea>
                </div>
            </div>

mishmar/templates/mishmar/arming_request_list.html
{% extends "mishmar/base.html" %}
{% block content %}

<ul>
        <h1> יומן חימוש בקשות שינוי</h1>
        <table class="responsive-table-input-matrix" style="align-items: center">
            <thead>
            <tr>
                <th>שם</th>
                <th>תאריך</th>
                <th>סטטוס</th>
            </tr>
            </thead>
            <tbody>
                <form method="POST">
                    {% csrf_token %}
                {% for arming in armingrequests %}
            <tr style="align-content: end">
                <td><a href="{% url 'arming-request' arming.id %}">{{arming.log|get_arming_name:arming }}</a></td>
                <td>{{arming.log.date|date:"d/m/Y" }}</td>
                {% if arming.read %}
                <td>טופל</td>
                {% else %}
                <td>ממתין לאישור</td>
                {% endif %}
            </tr>
            {% endfor %}
        </form>
            </tbody>
        </table>
</ul>
{% if is_paginated %}

{% if page_obj.has_previous %}
  <a class="btn btn-outline-info mb-4" href="?page=1">ראשון</a>
  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">קודם</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}
    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
  {% endif %}
{% endfor %}

{% if page_obj.has_next %}
  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">הבא</a>
  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">אחרון</a>
{% endif %}

{% endif %}
{% endblock content %}

mishmar/templates/mishmar/organization-ready.html
{% extends "mishmar/base.html" %}
{% block content %}
     <div>
        <h3 style="align-items: center">סידור לדוגמה בין תאריך {{ days|first|date:"d.m" }} לתאריך {{ days|last|date:"d.m" }}</h3>
            </div>
            <form method="post">
                {% csrf_token %}
            <button type="submit" name="back" id="back" class="btn btn-secondary">➜  חזרה לעריכה</button>
        </form>
    <div class="content-section row">
        <div style="margin-right: 1em">
<table class="responsive-table-input-matrix" style="align-items: center; margin-left: 10px">
		<thead>
        <tr>
			<th>תאריך</th>
            {% for day in days %}
                <th>{{ day|date:"d.m" }}</th>
                {% endfor %}
		</tr>
		<tr>
			<th></th>
			<th>ראשון</th>
			<th>שני</th>
			<th>שלישי</th>
			<th>רביעי</th>
			<th>חמישי</th>
			<th>שישי</th>
			<th>שבת</th>
		</tr>
		</thead>
		<tbody>
        {% for key in shifts %}
        <tr style="align-content: end">
            <td>{{ key.title }} <br> {% if key.sub_title != None %} {{key.sub_title}} {%endif %}</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
		</tbody>
	</table>
            </div>
    </div>
{% endblock content %}